# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eacf8f1b47ee23d052134257dcd838cb2eb204f69a75bb21f609e5ab5ffc8bf6c8937ae8be1a3c67fe5d0cce7f17f27012078f1dcc3647bf7d45bb5c3d3b44b

test:
  secret_key_base: 623fed6bd7de863e33d3bf639f68f35ba13eb979396ea589f23d883f4bf1456aafbd35c051f21d3ca8011f3be3af30e3d892f4edd7b183c76b68d22bfbdcc985

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
